/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#262a31',
        'primary-fixed-dim': '#00daf3',
        'on-tertiary-container': '#006731',
        'on-secondary': '#4c2700',
        'on-tertiary-fixed': '#00210b',
        'surface-container': '#1c2026',
        'surface-bright': '#353940',
        'on-error-container': '#ffdad6',
        'surface-variant': '#31353c',
        'on-tertiary': '#003918',
        secondary: '#ffb778',
        'on-secondary-fixed': '#2e1500',
        'surface-container-highest': '#31353c',
        'tertiary-fixed': '#62ff96',
        'secondary-fixed': '#ffdcc1',
        'inverse-surface': '#dfe2eb',
        'surface-container-low': '#181c22',
        'primary-container': '#00e5ff',
        outline: '#849396',
        'on-tertiary-fixed-variant': '#005226',
        'tertiary-fixed-dim': '#00e475',
        'on-background': '#dfe2eb',
        'tertiary-container': '#22ef7e',
        surface: '#10141a',
        'secondary-container': '#fd9000',
        'primary-fixed': '#9cf0ff',
        background: '#10141a',
        'on-primary-container': '#00626e',
        'error-container': '#93000a',
        primary: '#c3f5ff',
        'on-surface': '#dfe2eb',
        'on-surface-variant': '#bac9cc',
        'on-primary': '#00363d',
        'surface-dim': '#10141a',
        'surface-tint': '#00daf3',
        'on-primary-fixed': '#001f24',
        'surface-container-lowest': '#0a0e14',
        'on-error': '#690005',
        'outline-variant': '#3b494c',
        'secondary-fixed-dim': '#ffb778',
        'on-primary-fixed-variant': '#004f58',
        tertiary: '#b1ffbf',
        error: '#ffb4ab',
        'inverse-on-surface': '#2d3137',
        'inverse-primary': '#006875',
        'on-secondary-fixed-variant': '#6c3a00',
        'on-secondary-container': '#613400',
      },
      maxWidth: {
        '7xl': '80rem',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
